/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as AuthGithubImport } from './routes/auth/github'
import { Route as DashboardRepositoryRepoIDImport } from './routes/dashboard/repository/$repoID'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const AuthGithubRoute = AuthGithubImport.update({
  id: '/auth/github',
  path: '/auth/github',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRepositoryRepoIDRoute = DashboardRepositoryRepoIDImport.update({
  id: '/dashboard/repository/$repoID',
  path: '/dashboard/repository/$repoID',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/github': {
      id: '/auth/github'
      path: '/auth/github'
      fullPath: '/auth/github'
      preLoaderRoute: typeof AuthGithubImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/repository/$repoID': {
      id: '/dashboard/repository/$repoID'
      path: '/dashboard/repository/$repoID'
      fullPath: '/dashboard/repository/$repoID'
      preLoaderRoute: typeof DashboardRepositoryRepoIDImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/github': typeof AuthGithubRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/repository/$repoID': typeof DashboardRepositoryRepoIDRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/github': typeof AuthGithubRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/repository/$repoID': typeof DashboardRepositoryRepoIDRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/github': typeof AuthGithubRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/repository/$repoID': typeof DashboardRepositoryRepoIDRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/github'
    | '/auth'
    | '/dashboard'
    | '/dashboard/repository/$repoID'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/github'
    | '/auth'
    | '/dashboard'
    | '/dashboard/repository/$repoID'
  id:
    | '__root__'
    | '/'
    | '/auth/github'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/repository/$repoID'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthGithubRoute: typeof AuthGithubRoute
  AuthIndexRoute: typeof AuthIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardRepositoryRepoIDRoute: typeof DashboardRepositoryRepoIDRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthGithubRoute: AuthGithubRoute,
  AuthIndexRoute: AuthIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardRepositoryRepoIDRoute: DashboardRepositoryRepoIDRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/github",
        "/auth/",
        "/dashboard/",
        "/dashboard/repository/$repoID"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/github": {
      "filePath": "auth/github.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/dashboard/repository/$repoID": {
      "filePath": "dashboard/repository/$repoID.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
