name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./webui

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm ci

    - name: Check format
      run: |
        npm run format:check || \
        (echo "Bad formatting, run 'npm run format:write'")

    - name: Run linter
      run: npm run lint

    - name: Run build
      run: npm run build
